use std::fmt;

/// Errors generated by this crate
#[derive(Debug)]
pub enum Error {
    Message(String),
}
impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> Result<(), fmt::Error> {
        write!(
            f,
            "{:?}",
            match self {
                Error::Message(s) => s,
            }
        )
    }
}


impl From<config::ConfigError> for Error {
    fn from(e: config::ConfigError) -> Error {
        Error::Message(format!("configuration: {}",e.to_string()))
    }
}

impl From<handlebars::TemplateError> for Error {
    fn from(e: handlebars::TemplateError) -> Error {
        Error::Message(format!("template: {}",e.to_string()))
    }
}
impl From<handlebars::RenderError> for Error {
    fn from(e: handlebars::RenderError) -> Error {
        Error::Message(format!("template render: {}",e.to_string()))
    }
}
impl From<zenkit::Error> for Error {
    fn from(e: zenkit::Error) -> Error {
        Error::Message(format!("zenkit: {}",e.to_string()))
    }
}
impl From<std::io::Error> for Error {
    fn from(e: std::io::Error) -> Error {
        Error::Message(format!("IO: {}",e.to_string()))
    }
}

impl std::error::Error for Error {}
